# fetch remote db
DATABASE:
    host: '140.112.31.208'
    user: 'c2016'
    password: ''
    port: '3306'
    database: 'c2016'


# default sandbox config
BUTLER:
    host: '140.112.31.208'
    user: 'butler'
    period: 1

# This section is to ban forbidden words in source file with a threshold of cpu time.
#
# In this example, for any accepted submission which has cpu time lower than 1147(sec), we will check if there is any word "BAD_WORDS" in the source file.
# If so, the result of the submission will be RE with -1 in score.
BANNED_WORDS:
    word_list:
        - BAD_WORDS
    cpu_time_threshold: 1147

# This function will require non-release version of JudgeNode, default to disabled for compatibility.
STYLE_CHECK:
    enabled: False

# No usage if style check is disabled.
RBMQ:
    host: 'localhost'
    style_check_queue: 'style_check_task'
